version: "3.8"
services:
  next:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/root/app/
      - /root/app/node_modules
      - /root/app/.next
    command: sh -c "yarn && yarn dev -p 8000"
