name: stories-Github-page
on:
  push:
    branches:
      - main
      - releases/*

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: node -v
      # - run: npm install
      # - run: npm run storybook:gh -ci
