name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: Install fast-cli
        run: yarn global add fast-cli
      - name: Run fase cli
        run: fast -u
